version: '4'

networks:
    symfonyXdocker:

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfonyXdocker
        depends_on:
            - php
            - mysql
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - symfonyXdocker
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony_user
            MYSQL_ROOT_PASSWORD: s3cr3t_pwd
            MYSQL_PASSWORD: s3cr3t_pwd
        networks:
            - symfonyXdocker
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: s3cr3t
        networks:
            - symfonyXdocker
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: mailhog
        restart: always
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - symfonyXdocker
volumes: 
    mysql: